spring:
  application:
    name: testtask
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
          format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test-task
    username: postgres
    password: postgres
server:
  port: 8080